### ISSUE TITLE
インストール後、grubが起動しない

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/LUBS#11]
ライブ起動は問題なく行えますが、インストール後に起動しようとするとgrubが起動しません。真っ暗な画面のままフリーズします。
![image](https://user-images.githubusercontent.com/59412454/89967208-d7f5da80-dc8b-11ea-962a-732891175805.png)
使用したiso　https://drive.google.com/file/d/1vXSvt7uOTSd3HJriN_X1AcRHUXFmJTBI/view?usp=sharing

**Comment by 32x-k** [comment]
いろいろ試していたところ、リセットを何度か行うとgrub画面が表示されることがあるようです。ただ不安定で成功したりしなかったりします。

**Comment by 32x-k** [comment]
いろいろ試していたところ、リセットを何度か行うとgrub画面が表示されるようです。ただ不安定で成功したりしなかったりします。

**Comment by naoko1010hh** [comment]
ビルドした際のコミットハッシュの追記お願いいたします。

**Comment by 32x-k** [comment]
28b3f18a3236c6598937e416d7433406e55dc8c0 です。

**Comment by mkx419** [comment]
lightdmの修正を行ったところ無事起動するようになりました。
https://github.com/FascodeNet/LUBS/commit/ca0617f13e8fadd2aa80c824ba980e9a3806611e で修正
