### ISSUE TITLE
ビルド中にChromium で失敗する

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LUBS#3]
lubsのビルド中にErrors were encoutered while processing:というエラーが発生してビルドが停止する問題。

### エラー発生時のログのスクリーンショット↓
![https___s 0u0 biz_api_v4_image_url=https%3A%2F%2Fi gyazo com%2F1ad0304e2f62dc98f5ed280504a9cbd4](https://user-images.githubusercontent.com/50263013/82147986-6c6abf80-988c-11ea-858e-eed3d9d5bd73.png)

### 発生環境

仮想環境
CPU 1コア 使用率制限42%
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by naoko1010hh** [comment]
ビルド中に失敗することはなくなりましたがインストールされていない問題が発生しています。

**Comment by Hayao0819** [comment]
これってAlterLinuxですか？

**Comment by ghost** [comment]
最新のビルドでchromiumがインストールがされていない問題が再発しました。

**Comment by mkx419** [comment]
現在LUBSはsnapをサポートしていません
