### ISSUE TITLE
UEFI環境でgrubのインストールに失敗する。

### ISSUE THREAD

**Issue by namaomo1694** [FascodeNet/LUBS#4]
LubsでビルドをしたSerene Linuxをuefi環境でインストールしてみたところUbiquityのgrubのインストールに失敗し、手動で選択し直してもインストールをする事ができませんでした。

**Comment by ghost** [comment]
https://github.com/FascodeNet/LUBS/commit/bffeb67eae662c1cc39f82723c88b67859581e17 で修正
