### ISSUE TITLE
ユーザー名、ホストネームを変更できるようにしてほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LUBS#5]
デフォルトのユーザー名がubuntuのためそれをsereneなどの自由なユーザー名に変更できるようにしてほしい

**Comment by Hayao0819** [comment]
ホスト名は`airootfs`を使用して`/etc/hostname`を作成して下さい。
ユーザー名やパスワードは fa69c895edf9cc029cea066c4b6153e5b324ad65 で実装されました
