### ISSUE TITLE
xfce4-popup-whiskermenu が起動しない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LUBS#7]

**Comment by naoko1010hh** [comment]
![VirtualBox_lubs2_02_07_2020_16_11_11](https://user-images.githubusercontent.com/50263013/86327795-c974d600-bc7e-11ea-93e2-6cbbf879cc10.png)

**Comment by naoko1010hh** [comment]
コマンドラインから起動しても同じような画面になり一切起動しません

**Comment by ghost** [comment]
https://github.com/FascodeNet/LUBS/commit/e6e96870e9357cc9f8fedaebf24344d1b0c42045 で修正
