### ISSUE TITLE
インストーラーが立ち上がらない sorry,serenelinux 20.04 has experienced an internal error.

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/LUBS#8]
![VirtualBox_lubs2_03_07_2020_19_35_30](https://user-images.githubusercontent.com/50263013/86461301-c05e3480-bd64-11ea-9850-fb64155e5bbd.png)
![VirtualBox_lubs2_03_07_2020_19_36_46](https://user-images.githubusercontent.com/50263013/86461302-c0f6cb00-bd64-11ea-803a-042668ea19b7.png)
![VirtualBox_lubs2_03_07_2020_19_37_07](https://user-images.githubusercontent.com/50263013/86461306-c18f6180-bd64-11ea-9ec4-a6b16e73f4bd.png)
![VirtualBox_lubs2_03_07_2020_19_37_21](https://user-images.githubusercontent.com/50263013/86461307-c227f800-bd64-11ea-9d56-d42cb7c86e87.png)
![VirtualBox_lubs2_03_07_2020_19_37_31](https://user-images.githubusercontent.com/50263013/86461308-c227f800-bd64-11ea-99cd-584e656dfa61.png)
![VirtualBox_lubs2_03_07_2020_19_37_39](https://user-images.githubusercontent.com/50263013/86461309-c2c08e80-bd64-11ea-9813-af339d433b5f.png)
![VirtualBox_lubs2_03_07_2020_19_37_48](https://user-images.githubusercontent.com/50263013/86461312-c3592500-bd64-11ea-86e5-19e66b51eeac.png)

**Comment by naoko1010hh** [comment]
再起動し直したりすると表示されなかったりする。
不安定

**Comment by ghost** [comment]
https://github.com/FascodeNet/LUBS/commit/e6e96870e9357cc9f8fedaebf24344d1b0c42045 で修正
